variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  # Start interface in mock mode
  EPMT_GUI_MOCK: "1"
  # set display port to avoid crash
  DISPLAY: ":99"

cache:
  paths:
    - .cache/pip

build:interface:
  image: python:3.7.6
  script:
    - pip install --upgrade pip
    - pip install --trusted-host pypi.python.org -r requirements-ui.txt.py3
    # Start testing against mock interface
    # install google chrome
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
    - apt-get -y update
    - apt-get install -y google-chrome-stable
    # install chromedriver
    - apt-get install -yqq unzip
    - wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
    - unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
    # upgrade pip
    # install selenium after 
    - pip install selenium dash[testing]
    - echo "Start Mock Server"
    - python index.py & disown
    - echo "Point and click menus and buttons firing callbacks"
    - python test/find_and_click.py http://localhost:8050
    - echo "pytest url parser and generator"
    - pytest -q test/test_urlparse.py
