version: '3.1'

services:
  dash:
    image: dash:latest
    restart: always
    environment:
      ENV PYTHONUNBUFFERED: 0
    volumes:
      - ./:/home/dash
      - ./sample:/home/dash/sample
    ports:
      - 8050:8050