version: '3.1'
services:
  dash:
    image: epmt-interface:latest
    restart: always
    environment:
      ENV PYTHONUNBUFFERED: 0
    volumes:
      - ./:/home/dash
      - ./sample:/home/dash/sample
    ports:
      - 8050:8050

    test:
      build:
        context: .
        dockerfile: Dockerfiles/Dockerfile.chromedriver-sel
      command: /bin/bash -c 'cd /epmt && python ui/test/first_dash_test.py'
      volumes:
        - ./:/epmt
      links:
        - dash