FROM python:3.7.4

USER root
WORKDIR /home/dash
ADD requirements.txt requirements.txt.py3 /home/dash/
RUN pip install --trusted-host pypi.python.org -r requirements.txt -r requirements.txt.py3

EXPOSE 8050
ENV PYTHONUNBUFFERED 0
CMD ["python","-u","index.py"]